#!/bin/sh

COMMIT_MSG=`cat $1`
MSG_REGEX="^(feat|fix|docs|style|refactor|perf|test|workflow|build|ci|chore|release|workflow)(\(.+\))?!?: .{1,100}"

if ! echo "$COMMIT_MSG" | grep -qE "$MSG_REGEX"; then
  printf "\033[31mInvalid commit message format:\033[0m $COMMIT_MSG\
  \n\
  \nexample: 'feat(auth): add login and register functionality'\
  \n\
  \nSee https://github.com/woai3c/Front-end-articles/blob/master/git%20commit%20style.md for more details.\n"
  exit 1
fi

printf "\033[33mcommit message check passed\033[0m\n"

exit 0