#!/bin/sh

feat_flag=0
fix_flag=0

while read local_ref local_sha remote_ref remote_sha; do
    # use prev and current commit as new commits
    new_commits=$(git rev-list HEAD~~..${local_sha})

    if [ -n "$new_commits" ]; then
        for commit in $new_commits; do
            commit_msg=$(git log --format="%s" -n 1 $commit)
            if echo $commit_msg | grep -q "^feat"; then
                feat_flag=1
            elif echo $commit_msg | grep -q "^fix"; then
                fix_flag=1
            fi
        done
    else
        echo "No new commits found."
        exit 1
    fi
done

if [ $feat_flag -eq 1 ] && [ $fix_flag -eq 1 ]; then
    printf "\033[33mAll checks passed!\033[0m\n"
    exit 0
fi

printf "\033[31mCheck if you make two commits, and commit message should contain 'feat' and 'fix'\033[0m\n".
exit 1